# sme_pipeline.py
"""
Complete SME / Corporate Trade Finance Loan Processing Pipeline
10 agents: Intake → KYC → Financial Analysis → Credit Bureau → Collateral →
           Underwriting → Sanction → Documentation → Disbursement → Monitoring

Reads applicants from sme_applicants.json (generated by synthetic_data_generator.py)
"""
import random
from typing import Dict


# ── Agent 1 ──────────────────────────────────────────────────────────────────
class SMEIntakeAgent:
    """Lead Intake & Application Validation"""

    def process(self, data: Dict) -> Dict:
        vintage  = data.get("business_vintage_years", data.get("vintage", 0))
        turnover = data.get("annual_turnover", data.get("turnover", 0))
        loan_amt = data.get("loan_amount_requested", data.get("loan_amt", 0))
        valid    = vintage >= 3 and turnover >= 1_500_000
        return {
            "intake_valid":      valid,
            "turnover_ratio_ok": loan_amt <= turnover * 2,
            "lead_score":        round(60 + vintage * 4 + (turnover / 1_000_000) * 0.8, 1) if valid else 30.0,
            "status":            "intake_complete" if valid else "rejected-vintage/turnover",
        }


# ── Agent 2 ──────────────────────────────────────────────────────────────────
class SMEKycAgent:
    """KYC & Document Collection"""

    def process(self, data: Dict) -> Dict:
        success = random.random() < 0.90
        return {
            "kyc_status":       "complete" if success else "incomplete",
            "face_match_score": round(random.uniform(88, 99), 1) if success else 62.5,
            "kyc_risk_flags":   [] if success else ["PAN-Aadhaar mismatch"],
            "status":           "kyc_complete" if success else "kyc_pending",
        }


# ── Agent 3 ──────────────────────────────────────────────────────────────────
class SMEFinancialAnalysisAgent:
    """Financial Analysis – DSCR, ratios, GST & bank statement mock"""

    def process(self, data: Dict) -> Dict:
        turnover     = data.get("annual_turnover", data.get("turnover", 20_000_000))
        net_profit   = turnover * random.uniform(0.08, 0.18)
        depreciation = turnover * 0.07
        loan_amt     = data.get("loan_amount_requested", data.get("loan_amt", 0))
        debt_service = loan_amt * 0.14 or 1

        dscr          = round((net_profit + depreciation) / debt_service, 2)
        current_ratio = round(random.uniform(1.05, 2.9), 2)
        debt_equity   = round(random.uniform(1.2, 4.0), 2)
        gross_margin  = round(random.uniform(12, 28), 1)

        health = round(min(98, max(25,
            30 + min(dscr * 30, 40) + (current_ratio - 1) * 15 + (28 - abs(debt_equity - 2)) * 5
        )), 1)

        return {
            "dscr":                   dscr,
            "current_ratio":          current_ratio,
            "debt_to_equity":         debt_equity,
            "gross_profit_margin":    gross_margin,
            "financial_health_score": health,
            "status":                 "financial_analysis_complete",
        }


# ── Agent 4 ──────────────────────────────────────────────────────────────────
class SMECreditBureauAgent:
    """Credit Bureau & Promoter CIBIL"""

    def process(self, data: Dict) -> Dict:
        cibil = data.get("promoter_cibil_score", data.get("cibil", 680))
        grade = "A" if cibil >= 750 else "B" if cibil >= 700 else "C" if cibil >= 650 else "D"
        return {
            "promoter_cibil_score": cibil,
            "bureau_risk_grade":    grade,
            "status":               "bureau_complete",
        }


# ── Agent 5 ──────────────────────────────────────────────────────────────────
class SMECollateralAgent:
    """Collateral Verification & LTV Matrix"""

    LTV_MATRIX = {
        "term_loan":             70,
        "working_capital":       65,
        "equipment_finance":     55,
        "invoice_discounting":   80,
        "project_finance":       60,
        "residential_property":  75,
        "commercial_property":   65,
        "plant_machinery":       50,
    }

    def process(self, data: Dict) -> Dict:
        lt       = data.get("loan_type", data.get("type", "term_loan"))
        req      = data.get("loan_amount_requested", data.get("loan_amt", 0))
        col_val  = data.get("collateral_value", data.get("collateral", 0))
        if col_val == 0:
            col_val = req * random.uniform(1.3, 1.8)

        ltv     = round((req / max(col_val, 1)) * 100, 1)
        max_ltv = self.LTV_MATRIX.get(lt, 70)

        return {
            "collateral_value":  round(col_val, -3),
            "ltv_ratio":         ltv,
            "max_allowed_ltv":   max_ltv,
            "title_clear":       random.random() < 0.93,
            "collateral_status": "PASS" if ltv <= max_ltv + 5 else "REVIEW / FAIL",
            "status":            "collateral_verified",
        }


# ── Agent 6 ──────────────────────────────────────────────────────────────────
class SMEUnderwritingAgent:
    """Risk Scoring & Underwriting Decision Matrix"""

    def process(self, data: Dict) -> Dict:
        vintage = data.get("business_vintage_years", data.get("vintage", 0))
        cibil   = data.get("promoter_cibil_score", data.get("cibil", 650))
        dscr    = data.get("dscr", 1.0)
        health  = data.get("financial_health_score", 60)
        ltv     = data.get("ltv_ratio", 70)

        total = round(min(98, max(20,
            min(vintage * 2, 20) +
            min(max((cibil - 600) / 3, 0), 25) +
            min(max(dscr * 15, 0), 20) +
            health * 0.3 -
            max(0, (ltv - 65) * 0.5)
        )), 1)

        if total >= 80:   decision = "AUTO_APPROVE"
        elif total >= 65: decision = "APPROVE_WITH_CONDITIONS"
        elif total >= 50: decision = "REFER_TO_CREDIT_COMMITTEE"
        else:             decision = "REJECT"

        loan_amt = data.get("loan_amount_requested", data.get("loan_amt", 0))
        return {
            "total_score":         total,
            "risk_grade":          "AAA" if total >= 85 else "AA" if total >= 75 else "A" if total >= 65 else "BBB",
            "decision":            decision,
            "approved_loan_amount": round(loan_amt * 0.9, -3) if decision != "REJECT" else 0,
            "interest_rate":       11.75 if total >= 80 else 13.50 if total >= 65 else 15.75,
            "status":              "underwriting_complete",
        }


# ── Agent 7 ──────────────────────────────────────────────────────────────────
class SMESanctionAgent:
    """Sanction, Conditions & Approval"""

    def process(self, data: Dict) -> Dict:
        if data.get("decision") == "REJECT":
            return {"status": "not_applicable"}
        conditions = []
        if data.get("ltv_ratio", 0) > data.get("max_allowed_ltv", 70):
            conditions.append("Additional collateral required")
        if data.get("dscr", 1.5) < 1.25:
            conditions.append("Step-up repayment / moratorium suggested")
        return {
            "sanctioned_amount":       data.get("approved_loan_amount", 0),
            "final_interest_rate":     data.get("interest_rate", 13.0),
            "sanction_conditions":     conditions,
            "sanction_validity_days":  90,
            "status":                  "sanction_issued",
        }


# ── Agent 8 ──────────────────────────────────────────────────────────────────
class SMEDocumentationAgent:
    """Documentation, e-Sign & NACH"""

    def process(self, data: Dict) -> Dict:
        return {
            "docs_esigned":           True,
            "nach_umrn":              f"NACH{random.randint(100_000_000, 999_999_999)}",
            "nach_registered":        True,
            "documentation_complete": True,
            "status":                 "documentation_complete",
        }


# ── Agent 9 ──────────────────────────────────────────────────────────────────
class SMEDisbursementAgent:
    """Disbursement via RTGS / NEFT"""

    def process(self, data: Dict) -> Dict:
        if not data.get("documentation_complete", False):
            return {"status": "pending_docs"}
        amount = data.get("sanctioned_amount", 0)
        return {
            "disbursed_amount":    amount,
            "disbursement_mode":   "RTGS" if amount >= 200_000 else "NEFT",
            "loan_account_number": f"SME{random.randint(10_000_000, 99_999_999)}",
            "disbursement_status": "SUCCESS",
            "status":              "disbursed",
        }


# ── Agent 10 ─────────────────────────────────────────────────────────────────
class SMEMonitoringAgent:
    """Monitoring & NPA Management"""

    def process(self, data: Dict) -> Dict:
        dpd = random.randint(0, 45)
        return {
            "dpd_current":      dpd,
            "npa_risk_score":   round(random.uniform(8, 45), 1),
            "loan_health_score": round(100 - dpd * 1.8, 1),
            "status":           "monitoring_active",
        }


# ── Pipeline orchestrator ─────────────────────────────────────────────────────
class SMEPipeline:
    """Runs all 10 SME agents in sequence."""

    STAGES = [
        "intake", "kyc", "financial", "credit",
        "collateral", "underwriting", "sanction",
        "documentation", "disbursement", "monitoring",
    ]

    def __init__(self):
        self.agents = {
            "intake":        SMEIntakeAgent(),
            "kyc":           SMEKycAgent(),
            "financial":     SMEFinancialAnalysisAgent(),
            "credit":        SMECreditBureauAgent(),
            "collateral":    SMECollateralAgent(),
            "underwriting":  SMEUnderwritingAgent(),
            "sanction":      SMESanctionAgent(),
            "documentation": SMEDocumentationAgent(),
            "disbursement":  SMEDisbursementAgent(),
            "monitoring":    SMEMonitoringAgent(),
        }

    def run(self, application: Dict) -> Dict:
        state = application.copy()
        # Normalise key aliases from JSON schema
        if "turnover" in state and "annual_turnover"          not in state:
            state["annual_turnover"] = state["turnover"]
        if "vintage"  in state and "business_vintage_years"   not in state:
            state["business_vintage_years"] = state["vintage"]
        if "loan_amt" in state and "loan_amount_requested"    not in state:
            state["loan_amount_requested"] = state["loan_amt"]
        if "type"     in state and "loan_type"                not in state:
            state["loan_type"] = state["type"]
        if "cibil"    in state and "promoter_cibil_score"     not in state:
            state["promoter_cibil_score"] = state["cibil"]
        if "collateral" in state and "collateral_value"       not in state:
            state["collateral_value"] = state["collateral"]

        state["logs"]          = []
        state["stage_history"] = []

        for stage in self.STAGES:
            result = self.agents[stage].process(state)
            state.update(result)
            state["logs"].append(
                f"[{stage.upper():15s}] "
                f"{result.get('status', result.get('disbursement_status', 'done'))}"
            )
            state["stage_history"].append(stage)
            if result.get("decision") == "REJECT" or result.get("intake_valid") is False:
                break

        return state


# ── Standalone test ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    import json
    with open("sme_applicants.json", encoding="utf-8") as f:
        samples = json.load(f)
    result = SMEPipeline().run(samples[0])
    print("Decision  :", result.get("decision"))
    print("DSCR      :", result.get("dscr"))
    print("Score     :", result.get("total_score"))
    print("NACH UMRN :", result.get("nach_umrn"))
    for log in result["logs"]:
        print(" ", log)
